development:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: progress_development
  username: root
  password:
  pool: 5
  
test:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: progress_test
  username: root
  password:
  pool: 5
  
staging:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: progress_staging
  username: root
  password:
  pool: 5
  
production:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: progress_production
  username: root
  password:
  pool: 5