development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Metaphoe
  admin_email: admin@cultureamp.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://progress-staging.heroku.com
  site_name: Progress
  admin_email: admin@cultureamp.com  
  
production:
  site_url: http://progress-production.heroku.com
  site_name: Progress
  admin_email: admin@cultureamp.com
